<div class="main-index">
    <div class="form">
        <legend>Kupac id:<?=$customer->id?></legend>
    <hr>
    
    <div class="large-6 cell">
        <label for="firstname">Ime</label>
        <p><?= $customer->firstname ?></p>

        <label for="lastname">Prezime</label>
        <p><?= $customer->lastname ?></p>

        <label for="email">Email</label>
        <p><?= $customer->email ?></p>
    </div>
    <div class="large-6 cell">
        <label for="phonenumber">Broj telefona</label>
        <p><?= $customer->phonenumber ?></p>

        <label for="street">Ulica i kućni broj</label>
        <p><?= $customer->street ?></p>

        <label for="city">Grad i poštanski broj</label>
        <p><?= $customer->city ?> <?= $customer->postalnumber ?></p>

    </div>
    </div>
</div>