<div class="main-index">
<h1 style="font-size: 1.5rem;">Popis kupaca</h1>
<hr>
    <form class="search-product large-6 cell" action="<?= App::config('url') ?>customer/index" method="get">
        <div>
            <input type="radio" id="normal" name="negation" value="0" <?= ($negation == '0') ? 'checked' : ''; ?>>
            <label for="normal">Normalno</label>
            <input type="radio" id="negation" name="negation" value="1" <?= ($negation == '1') ? 'checked' : ''; ?>>
            <label for="negation">Negacija <i class="fas fa-info-circle" title="Svi koji nemaju traženu vrijednost."></i></label>
        </div>
        <div class="ui-widget">
            <input type="text" id="search" name="search" class="search-product" placeholder="Traži po imenu, prezimenu ili gradu." value="<?= (isset($_GET['search'])) ? $_GET['search'] . '"' : '' ?>">
        </div>
        <input style="margin-bottom:10px; width: 100%;" type="submit" class="button" value="Traži!">
    </form>
    <?php if ($totalCustomers == 1) : ?>
        <legend class="total-product-message">Pronađen samo jedan kupac.</legend>
    <?php else : ?>
        <legend class="total-product-message">Pronađeno ukupno <?= $totalCustomers ?> kupaca.</legend>
    <?php endif; ?>
    <?php if ($totalCustomers != 0) : ?>
    <table>
        <thead>
            <tr>
                <th>Ime i prezime</th>
                <th>Email</th>
                <th>Grad</th>
                <th>Zadnji put online</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($customers as $c) : ?>
                <tr>
                    <td><?= $c->firstname ?> <?= $c->lastname ?></td>
                    <td><?= $c->email ?></td>
                    <td><?= $c->city ?></td>
                    <td><?= $c->lastOnline ?></td>
                    <td>
                        <a href="<?= App::config('url') ?>customer/details/<?= $c->id ?>" class="button expand info">View details...</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php include 'pagination.phtml' ?>
    <?php endif; ?>
</div>