<div class="main-index">
<form class="search-product large-6 cell blue-sky" action="<?= App::config('url') ?>customer/index" method="get">
        <div class="ui-widget">
            <input type="text" name="search" id="search" class="search-product" placeholder="Traži po imenu, prezimenu, gradu, proizvodu, proizvođaču, kategoriji..." <?= (isset($_GET['search'])) ? 'value="' . $_GET['search'] . '"' : '' ?>>
        </div>
    </form>
    <?php if($totalCustomers == 1):?>
    <legend class="total-product-message">Pronađen samo jedan kupac.</legend>
    <?php else:?>
    <legend class="total-product-message">Pronađeno ukupno <?=$totalCustomers?> kupaca.</legend>
    <?php endif;?>
<table>
        <thead>
            <tr>
                <th>Naziv</th>
                <th>Opis</th>
                <th>Zadnja put online</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($customers as $c) : ?>
                <tr>
                    <td><?= $c->firstname ?> <?=$c->lastname?></td>
                    <td><?= $c->email ?></td>
                    <td><?= $c->lastOnline ?></td>
                    <td>
                        <a href="<?= App::config('url') ?>customer/details/<?= $c->id ?>" class="button expand info">View details...</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>