<div class="index-main">
    <h2 class="text-center">🥵🥵🥵 Najprodavaniji proizvodi 🥵🥵🥵</h2>
    <div class="grid-x grid-padding-x">
        <?php foreach ($mostSoldProductList as $product) : ?>
            <div class="large-3">
                <div class="card">
                    <div class="card-divider" data-open="product<?= $product->id ?>" title="Kliknite na sliku za detalje!">
                        <span>
                            <?= $product->name ?>
                        </span>
                    </div>
                    <img src="<?= $product->imageurl ?>" data-open="product<?= $product->id ?>" title="Kliknite na sliku za detalje!">
                    <hr>
                    <div class="card-section">
                        <h4><?= $product->price ?> kn
                            <i class="fas fa-cart-plus add-to-cart" title="<?= (isset($_SESSION['authorized'])) ? 'Dodaj u košaricu.' : 'Prijavite se ili registrirajte za dodavanje ' . $product->name . ' u Vašu košaricu.'; ?>"></i>
                            <i class="far fa-heart add-to-wishlist" title="<?= (isset($_SESSION['authorized'])) ? 'Dodaj u listu želja.' : 'Prijavite se ili registrirajte za dodavanje ' . $product->name . ' u Vašu listu želja.'; ?>"></i>
                        </h4>
                    </div>
                    <div class="small reveal" id="product<?= $product->id ?>" data-reveal>
                        <h1 class="modal-product-name"><?= $product->name ?></h1>
                        <div class="grid-x grid-padding-x modal-product-section">
                            <div class="large-6 modal-product-image">
                                <img src="<?= $product->imageurl ?>" alt="<?= $product->name ?>">
                            </div>
                            <div class="large-6 modal-product-description">
                                <p><?= $product->description ?></p>
                            </div>
                        </div>
                        <div class="grid-x grid-padding-x text-center">
                            <div class="large-6 large-offset-1">
                                <h3><?= $product->price ?> kn</h3>
                            </div>
                            <div class="large-3">
                                <i class="fas fa-3x fa-cart-plus add-to-cart" title="<?= (isset($_SESSION['authorized'])) ? 'Dodaj u košaricu.' : 'Prijavite se ili registrirajte za dodavanje ' . $product->name . ' u Vašu košaricu.'; ?>"></i>
                                <i class="far fa-3x fa-heart add-to-wishlist" title="<?= (isset($_SESSION['authorized'])) ? 'Dodaj u listu želja.' : 'Prijavite se ili registrirajte za dodavanje ' . $product->name . ' u Vašu listu želja.'; ?>"></i>
                            </div>
                        </div>
                        <button class="close-button" data-close aria-label="Close modal" type="button">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <br>
    <br>
    <h2 class="text-center">🔥🔥🔥 Novo u ponudi! 🔥🔥🔥</h2>
    <div class="grid-x grid-padding-x">
        <?php foreach ($newestProductList as $product) : ?>
            <div class="large-3">
                <div class="card">
                    <div class="card-divider" data-open="product<?= $product->id ?>" title="Kliknite na sliku za detalje!">
                        <span>
                            <?= $product->name ?>
                        </span>
                    </div>
                    <img src="<?= $product->imageurl ?>" data-open="product<?= $product->id ?>" title="Kliknite na sliku za detalje!">
                    <hr>
                    <div class="card-section">
                        <h4><?= $product->price ?> kn
                            <i class="fas fa-cart-plus add-to-cart" title="<?= (isset($_SESSION['authorized'])) ? 'Dodaj u košaricu.' : 'Prijavite se ili registrirajte za dodavanje ' . $product->name . ' u Vašu košaricu.'; ?>"></i>
                            <i class="far fa-heart add-to-wishlist" title="<?= (isset($_SESSION['authorized'])) ? 'Dodaj u listu želja.' : 'Prijavite se ili registrirajte za dodavanje ' . $product->name . ' u Vašu listu želja.'; ?>"></i>
                        </h4>
                    </div>
                    <div class="small reveal" id="product<?= $product->id ?>" data-reveal>
                        <h1 class="modal-product-name"><?= $product->name ?></h1>
                        <div class="grid-x grid-padding-x modal-product-section">
                            <div class="large-6 modal-product-image">
                                <img src="<?= $product->imageurl ?>" alt="<?= $product->name ?>">
                            </div>
                            <div class="large-6 modal-product-description">
                                <p><?= $product->description ?></p>
                            </div>
                        </div>
                        <div class="grid-x grid-padding-x text-center">
                            <div class="large-6 large-offset-1">
                                <h3><?= $product->price ?> kn</h3>
                            </div>
                            <div class="large-3">
                                <i class="fas fa-3x fa-cart-plus add-to-cart" title="<?= (isset($_SESSION['authorized'])) ? 'Dodaj u košaricu.' : 'Prijavite se ili registrirajte za dodavanje ' . $product->name . ' u Vašu košaricu.'; ?>"></i>
                                <i class="far fa-3x fa-heart add-to-wishlist" title="<?= (isset($_SESSION['authorized'])) ? 'Dodaj u listu želja.' : 'Prijavite se ili registrirajte za dodavanje ' . $product->name . ' u Vašu listu želja.'; ?>"></i>
                            </div>
                        </div>
                        <button class="close-button" data-close aria-label="Close modal" type="button">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>