<div class="index-main">
    <h2 class="text-center">🥵🥵🥵 Najprodavaniji proizvodi 🥵🥵🥵</h2>
    <div class="grid-x grid-padding-x">
        <?php foreach ($mostSoldProductList as $product) : ?>
            <!-- Product card -->
            <?php include 'public/product/productcard.phtml'; ?>
            <!--  -->
        <?php endforeach; ?>
    </div>
    <br>
    <br>
    <h2 class="text-center">🔥🔥🔥 Novo u ponudi! 🔥🔥🔥</h2>
    <div class="grid-x grid-padding-x">
        <?php foreach ($newestProductList as $product) : ?>
            <!-- Product card -->
            <?php include 'public/product/productcard.phtml'; ?>
            <!--  -->
        <?php endforeach; ?>
    </div>
</div>
