<form class="log-in-form" action="<?= App::config('url') ?>login/authorize" method="POST">
    <h4 class="text-center">Prijava</h4>
    <p class="text-center">Ukoliko nemate račun, registrirajte se <a href="<?= App::config('url') ?>registration/index">ovdje.</a></p>
    <label>Email
        <input type="email" name="email" placeholder="marija@edunova.hr" value="<?= $email ?>" />
    </label>
    <label>Lozinka
        <input type="password" name="user_password" />
    </label>
    <p>
        <input type="submit" class="button expanded" value="Prijava" />
    </p>
    <?= $message ?>
</form> 

<div>
    Uloga: admin
    <br>
    Email: admin@edunova.hr
    <br>
    Lozinka: a
    <br>
    <br>
    Uloga: operator
    <br>
    Email: oper@edunova.hr
    <br>
    Lozinka: o
    <br>
    <br>
    Uloga: kupac
    <br>
    Email: blingblong@gmail.com
    <br>
    Lozinka: a
    <br>
    <br>
</div>