<form class="log-in-form" action="<?= App::config('url') ?>login/authorize" method="POST">
    <h4 class="text-center">Prijava</h4>
    <p class="text-center">Ukoliko nemate račun, registrirajte se <a href="<?= App::config('url') ?>registration/index">ovdje.</a></p>
    <label>Email
        <input type="email" name="email" placeholder="marija@edunova.hr" id="email" aria-describedby="messageEmail" value="<?= $email ?>" />
    </label>
    <p class="help-text red-message" id="messageEmail">
        <?= $message->email ?>
    </p>
    <label>Lozinka
        <input type="password" name="user_password" id="user_password" aria-describedby="messagePassword"/>
    </label>
    <p class="help-text red-message" id="messagePassword" >
        <?= $message->password ?>
    </p>
    <p>
        <input type="submit" class="button expanded" value="Prijava" />
    </p>
    <?php if (isset($message->logout)):?>
        <p class="help-text red-message">
        <?= $message->logout ?>
        </p>
    <?php endif;?>
</form> 

<div>
    Uloga: admin
    <br>
    Email: admin@edunova.hr
    <br>
    Lozinka: a
    <br>
    <br>
    Uloga: operator
    <br>
    Email: oper@edunova.hr
    <br>
    Lozinka: o
    <br>
    <br>
    Uloga: kupac
    <br>
    Email: blingblong@gmail.com
    <br>
    Lozinka: a
    <br>
    <br>
</div>