<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Including head.phtml -->
    <?php include 'includes/head.phtml'?>
</head>

<body>
    <!-- Including navigation bar depending whether it is customer or admin/oper -->
    <?php 
        if(isset($_SESSION['authorized']->user_role) && ($_SESSION['authorized']->user_role == 'admin' || $_SESSION['authorized']->user_role == 'oper')){
            include_once 'includes/adminNavbar.phtml';
        }else{
            include_once 'includes/publicNavbar.phtml';
        }
    ?>

    <!-- Main view -->
    <?php if(isset($_SESSION['authorized']->user_role) && ($_SESSION['authorized']->user_role == 'admin' || $_SESSION['authorized']->user_role == 'oper')):?>
    <div class="main grid-container">
    <?php else:?>
    <div class="grid-container">
    <?php endif;?>
        <div class="grid-x grid-padding-x">
            <div class="large-12 cell">
                <div class="callout" id="content">
                    <!-- Content from controllers is displayed here -->
                    <?= $content ?>
                </div>
            </div>
        </div>
    </div>

    <!-- Including javacsript and other scripts -->
    <?php include_once 'includes/script.phtml'?>
    <?php include_once 'includes/footer.phtml'?>
</body>

</html> 