<h1 class="text-center">Dobrodošli, <?= $customer->firstname ?></h1>
<hr>
<?php if($change==1):?>
    <h4 class="green-message text-center">Lozinka uspješno promijenjena!</h4>
<?php endif;?>
<div class="grid-x grid-padding-x dashboard-profil">
    <div class="large-6 cell">
        <label for="firstname">Ime</label>
        <p><?= $customer->firstname ?></p>

        <label for="lastname">Prezime</label>
        <p><?= $customer->lastname ?></p>

        <label for="email">Email</label>
        <p><?= $customer->email ?></p>
    </div>
    <div class="large-6 cell">
        <label for="phonenumber">Broj telefona</label>
        <p><?= $customer->phonenumber ?></p>

        <label for="street">Ulica i kućni broj</label>
        <p><?= $customer->street ?></p>

        <label for="city">Grad i poštanski broj</label>
        <p><?= $customer->city ?> <?= $customer->postalnumber ?></p>

    </div>
</div>
<div class="text-center">
    <a class="button expand info dashboard-update-button" href="<?= App::config('url') ?>dashboard/details" >Promijeni podatke</a>
    <a class="button expand secondary dashboard-update-button" href="<?= App::config('url') ?>dashboard/passwordchange" >Promijeni lozinku</a>
</div>
<hr>
<?php include 'orders.phtml';?>