<div class="details-form">
    <form action="<?= App::config('url') ?>dashboard/updatepassword"  method="POST">
        <div class="text-center dashboard-update-reveal">

            <legend>Obavezna polja</legend>

            <input type="hidden" name="id" value="<?= $customer->id ?>">
            <label for="oldpassword">Trenutna lozinka</label>
            <input type="password" name="oldpassword" id="oldpassword" aria-describedby="messageoldpassword" value="<?=$password->oldpassword?>">
            <p class="help-text red-message" id="messageoldpassword">
                <?= $message->oldpassword ?>
            </p>

            <label for="newpassword">Nova lozinka</label>
            <input type="password" name="newpassword" id="newpassword" aria-describedby="messagenewpassword" value="<?=$password->newpassword?>">
            <p class="help-text red-message" id="messagenewpassword">
                <?= $message->newpassword ?>
            </p>

            <label for="newpasswordrepeat">Nova lozinka ponovno</label>
            <input type="password" name="newpasswordrepeat" id="newpasswordrepeat" aria-describedby="messagenewpasswordrepeat">
            <p class="help-text red-message" id="messagenewpasswordrepeat">
                <?= $message->newpasswordrepeat ?>
            </p>
        </div>
        <div class="grid-x grid-padding-x reveal-buttons">
            <div class="large-6 cell">
                <a class="alert button expanded" href="<?= App::config('url') ?>dashboard/index">Natrag.</a>
            </div>
            <div class="large-6 cell">
                <input type="submit" class="blue-sky button expanded" value="Sačuvaj promijene.">
            </div>
        </div>
    </form>
</div>