<div class="grid-x">
    <div class="cell large-6">
        <h1 style="font-size: 1.5rem;">Kategorije</h1>
    </div>
    <div class="cell large-6" style="text-align: right;">
        <a href="<?=App::config('url')?>category/new"><i style="color: green;" title="Dodaj novu kategoriju." class="fas fa-2x fa-plus-circle"></i></a>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Opis</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($categories as $category):?>
        <tr>
            <td><?=$category->name?></td>
            <td><?=$category->description?></td>
            <td>
                    <?php if($category->hasproducts == 0):?>
                        <a onclick="return confirm('Sigurno obrisati <?=$category->name?> ?')" style="margin-left: 20px; color: red;" href="<?=App::config('url')?>category/delete/<?=$category->id?>"><i title="Obriši &quot;<?=$category->name?>&quot;." class="fas fa-2x fa-trash"></i></a>
                    <?php else:?>
                        <i style="margin-left: 20px; color: gray;" title="Ne moze se obrisati &quot;<?=$category->name?>&quot; jer ima proizvode." class="fas fa-2x fa-trash"></i>
                    <?php endif;?>
                </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>