<div class="product-form">
<form action="<?= App::config('url') ?>product/action" method="POST" enctype="multipart/form-data">
    <?php if($product->id != 0):?>        
    <div>
        <a onclick="return confirm('Confirm deletion for <?=$product->name?> ?')" class="warning button expanded" href="<?=App::config('url')?>product/delete/<?=$product->id?>">Obriši proizvod!</a>     
    </div>
    <hr>
    <?php endif;?>

    <legend>Detalji proizvoda:</legend>
    <input type="hidden" name="id" value="<?=$product->id?>">
    
    <label for="name">Naziv</label>
    <input type="text" name="name" id="name" aria-describedby="messagename" value="<?= $product->name ?>">
    <p class="help-text red-message" id="messagename">
        <?= $message->name ?>
    </p>

    <label for="description">Opis</label>
    <input type="text" name="description" id="description" aria-describedby="messagedescription" value="<?= $product->description ?>">
    <p class="help-text red-message" id="messagedescription">
        <?= $message->description ?>
    </p>

    <label for="category">Kategorija</label>
    <select id="category" name="category" aria-describedby="messagecategory">
        <option value="0">Odaberite kategoriju</option>
        <?php foreach ($categories as $category) : ?>
                <option value="<?= $category->id ?>" <?php if($category->id == $product->category) echo 'selected="selected"';?>><?= $category->name ?></option>
        <?php endforeach; ?>
    </select>
    <p class="help-text red-message" id="messagecategory">
        <?= $message->category ?>
    </p>

    <label for="manufacturer">Proizvođač</label>
    <select id="manufacturer" name="manufacturer" aria-describedby="messagemanufacturer">
        <option value="0">Odaberite proizvođača</option>
        <?php foreach ($manufacturers as $manufacturer) : ?>
                <option value="<?= $manufacturer->id ?>" <?php if($manufacturer->id == $product->manufacturer) echo 'selected="selected"';?>><?= $manufacturer->name ?></option>
        <?php endforeach; ?>
    </select>
    <p class="help-text red-message" id="messagemanufacturer">
        <?= $message->manufacturer ?>
    </p>

    <label for="price">Cijena (npr. 125,99)</label>
    <input type="text" name="price" id="price" aria-describedby="messageprice" value="<?= $product->price ?>">
    <p class="help-text red-message" id="messageprice">
        <?= $message->price ?>
    </p>

    <label for="inventoryquantity">Stanje u skladištu</label>
    <input type="number" name="inventoryquantity" id="inventoryquantity" aria-describedby="messageinventoryquantity" value="<?= $product->inventoryquantity ?>">
    <p class="help-text red-message" id="messageinventoryquantity">
        <?= $message->inventoryquantity ?>
    </p>

    <label for="imageInput">* Klik na sliku za promjenu slike *</label>
    <input type="hidden" name="imageInput" id="imageInput" value="<?= $product->imageInput?>" aria-describedby="messageimageinput">
    <p class="help-text red-message" id="messageimageinput">
        <?= $message->imageInput ?>
    </p>
    <img class="picture" id="photo" src="<?= App::config('url')?>public/images/product/<?=$product->id?>.png" alt="<?=$product->name?>">
    <br>

    <!-- Modal for CropperJS -->
    <div class="reveal" id="pictureModal" data-reveal>
        <div style="max-height: 600px; overflow: auto;">
            <img id="image" src="" alt="" />
        </div>
        <br>
        <input type="file" id="inputImage" name="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">
        <br>
        <div class="grid-x text-center">
            <div class="large-8 text-center">
                <a class="button expanded" href="#" id="save">Spremi</a>
            </div>
            <div class="large-4 text-center">
                <button class="button alert" data-close aria-label="Close modal" >Odustani</button>
            </div>
        </div>
    </div>
    <!-- End modal -->
<br>
    <div class="grid-x grid-padding-x">
        <div class="large-5 cell">
            <a class="alert button expanded" href="<?= App::config('url') ?>product/index">Natrag.</a>
        </div>
        <div class="large-7 cell">
            <input type="submit" class="info button expanded" id="submitForm" value="<?= $action ?>">
        </div>
    </div>
</form>
</div>

