<div class="main-index">
    <div class="grid-x">
    <div class="cell large-6">
        <h1 style="font-size: 1.5rem;">Products</h1>
    </div>
    <div class="cell large-6" style="text-align: right;">
        <a href="<?=App::config('url')?>product/details"><i style="color: green;" title="Add new product" class="fas fa-2x fa-plus-circle"></i></a>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Naziv</th>
            <th>Proizvođač</th>
            <th>Kategorija</th>
            <th>Cijena</th>
            <th class="text-center">Stanje</th>
            <th>Zadnja izmjena</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($products as $product):?>
        <tr>
            <td><?=$product->id?></td>
            <td><?=$product->name?></td>
            <td><?=$product->manufacturer?></td>
            <td><?=$product->category?></td>
            <td><?=$product->price?> kn</td>
            <td class="text-center"><?=$product->inventoryquantity?></td>
            <td><?=$product->lastUpdated?></td>
            <td>
              <a href="<?= App::config('url') ?>product/details/<?= $product->id ?>" class="button expand info">View details...</a>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>
</div>


