<div class="main-index">
    <div class="grid-x">
        <div class="cell large-6">
            <h1 style="font-size: 1.5rem;">Proizvodi</h1>
        </div>
        <div class="cell large-6" style="text-align: right;">
            <a href="<?= App::config('url') ?>product/details"><i style="color: green;" title="Add new product" class="fas fa-2x fa-plus-circle"></i></a>
        </div>
    </div>
    <hr>
    <form class="search-product large-6 cell blue-sky" action="<?= App::config('url') ?>product/index" method="get">
        <div class="ui-widget">
            <input type="text" name="search" id="search" class="search-product" placeholder="Traži po id, imenu proizvoda, proizvođaču, kategoriji..." <?= (isset($_GET['search'])) ? 'value="' . $_GET['search'] . '"' : '' ?>>
        </div>
    </form>
    <?php if($totalProducts == 1):?>
    <legend class="total-product-message">Pronađen samo jedan proizvod.</legend>
    <?php else:?>
    <legend class="total-product-message">Pronađeno ukupno <?=$totalProducts?> proizvoda.</legend>
    <?php endif;?>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Naziv</th>
                <th>Proizvođač</th>
                <th>Kategorija</th>
                <th>Cijena</th>
                <th class="text-center">Stanje</th>
                <th class="text-center">Zadnja izmjena</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($products as $product) : ?>
                <tr>
                    <td><?= $product->id ?></td>
                    <td><?= $product->name ?></td>
                    <td><?= $product->manufacturer ?></td>
                    <td title="<?=$product->category?>"><?= (strlen($product->category) > 13) ? substr($product->category,0,10).'...' : $product->category;?></td>
                    <td><?= $product->price ?> kn</td>
                    <td class="text-center"><?= $product->inventoryquantity ?></td>
                    <td><?= $product->lastUpdated ?></td>
                    <td>
                        <a href="<?= App::config('url') ?>product/details/<?= $product->id ?>" class="button expand info">View details...</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php include 'pagination.phtml' ?>
</div>