<div class="main-index">
    <div class="grid-x">
        <div class="cell large-6">
            <h1 style="font-size: 1.5rem;">Kategorije</h1>
        </div>
        <div class="cell large-6" style="text-align: right;">
            <a href="<?= App::config('url') ?>category/details"><i style="color: green;" title="Dodaj novu kategoriju." class="fas fa-2x fa-plus-circle"></i></a>
        </div>
    </div>
    <table>
        <thead>
            <tr>
                <th>Naziv</th>
                <th>Opis</th>
                <th>Zadnja promjena</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($categories as $category) : ?>
                <tr>
                    <td><?= $category->name ?></td>
                    <td><?= $category->description ?></td>
                    <td><?= $category->lastUpdated ?></td>
                    <td>
                        <a href="<?= App::config('url') ?>category/details/<?= $category->id ?>" class="button expand info">View details...</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>