<div class="grid-x grid-padding-x">
  <div class="large-2 large-offset-1">
    <form action="<?=App::config('url')?>/product/index" method="get">
      <div class="manufacturer-filter">
        <legend>Manufacturer</legend>
        <div class="manufacturer-list">
        <?php foreach($manufacturers as $m):?>
          <input type="radio" id="manufacturerId<?=$m->id?>" name="manufacturer" value="<?=$m->id?>">
          <label for="manufacturerId<?=$m->id?>"><?=$m->name?></label><br>
        <?php endforeach;?>
        </div>
        <div class="manufacturer-list-button">
          <input type="submit" class="button blue-sky" value="Search!">
        </div>
      </div>
    </form>
  </div>
  <div class="large-7">
    <!-- Showing user how many products meets their search specification -->
    <p class="total-product-message">
      <?php if($totalProducts < 2):?>
      Jedan proizvod zadovoljava Vaše specifikacije.
      <?php else:?>
        Pronađeno ukupno <?=$totalProducts?> proizvoda.
        Prikazujemo proizvode od <?= $page*App::config('ppp')-App::config('ppp')+1?> do 
        <?php if($page*App::config('ppp') > $totalProducts){
          echo $totalProducts;
        }else{
          echo $page*App::config('ppp').'.';
        }?>
        <?php endif;?>
    </p>
    <!--  -->
    <div class="grid-x grid-padding-x product-grid">
      <?php foreach ($products as $product) : ?>
        <!-- Product card  -->
        <?php include 'product.phtml'?>
        <!--  -->
      <?php endforeach; ?>
    </div>
  </div>
  <div class="large-2 cell">
  </div>
</div>
<!-- Customer product pagination -->
<?php include 'pagination.phtml'?>
<!--  -->