<div class="grid-x grid-padding-x">
  <div class="large-2 large-offset-1">

  </div>
  <div class="large-7">
    <div class="grid-x grid-padding-x product-grid">
      <?php foreach ($products as $product) : ?>
        <!-- Product card  -->
        <?php include 'product.phtml'?>
        <!--  -->
      <?php endforeach; ?>
    </div>
  </div>
  <div class="large-2 cell">
  </div>
</div>
<!-- Customer product pagination -->
<?php include 'pagination.phtml'?>
<!--  -->