<div class="reveal" id="productprijava" data-reveal>
      <div class="login-form login-modal" data-alignment="center">
      <form class="log-in-form" action="<?= App::config('url') ?>login/authorize" method="POST">
      <h4>Ukoliko želite nastaviti, prijavite se ili registrirajte <a href="<?= App::config('url') ?>registration/index">ovdje.</a></h4>
      <br>
                    <label for="email">Vaš email</label>
                    <input type="email" name="email" id="email" class="log-in-form-input" aria-describedby="messageEmail" placeholder="vas.email@gmail.com" value="<?= $email ?>">
                    <p class="help-text red-message" id="messageEmail">
                        <?= $message->email ?>
                    </p>
                    <label for="user_password">Vaša lozinka</label>
                    <input type="password" name="user_password" id="user_password" class="log-in-form-input" aria-describedby="messagePassword">
                    <p class="help-text red-message" id="messagePassword">
                        <?= $message->password ?>
                    </p>

                    <input type="hidden" name="currentPage" value="<?= substr($_SERVER['REQUEST_URI'], 1) ?>">
                    <div class="text-center ">
                    <input type="submit" class="expanded prijava-button" value="Prijava" />
                    </div>
                    
                    <?php if (isset($message->logout)) : ?>
                        <p class="help-text red-message">
                            <?= $message->logout ?>
                        </p>
                    <?php endif; ?>
                </form>
                <button class="close-button" data-close aria-label="Close modal" type="button">
                    <span aria-hidden="true">&times;</span>
                </button>
                <br>
                <ul class="text-center" style="list-style:none;">
                    <li>* Ekskluzivni popusti za članove kluba</li>
                    <li>* Brzo i jednostavno naručivanje</li>
                    <li>* Pratite svoje narudžbe i njihovu povijest</li>
                </ul>
                <hr>
                    Uloga: kupac
                <br>
                Email: r.knezevic@mojatrgovina.com
                <br>
                Lozinka: a
                <br>
                <br>
                Uloga: admin
                <br>
                Email: admin@edunova.hr
                <br>
                Lozinka: a
                <br>
                <br>
                Uloga: operator
                <br>
                Email: oper@edunova.hr
                <br>
                Lozinka: o
                <br>
                <br>
      </div>
    </div>