<div class="large-3">
  <div class="card">
    <div class="card-divider" data-open="product<?= $product->id ?>" title="Kliknite na sliku za detalje!">
      <span>
        <?= $product->name ?>
      </span>
    </div>
    <img src="<?= App::config('url')?>public/images/product/<?= $product->id?>.png" data-open="product<?= $product->id ?>" title="Kliknite na sliku za detalje!">
    <hr>
    <div class="card-section">
      <h4><?= $product->price ?> kn
        <?php if (App::authorized()) : ?>
          <i class="fas fa-cart-plus add-to-cart addToCart" data-id="<?= $product->id ?>" data-open="modal<?=$product->id?>" title="Dodaj &quot;<?= $product->name ?>&quot; u košaricu"></i>
          <div class="small reveal add-modal" id="modal<?=$product->id?>" data-reveal>
            <div class="grid-x grid-padding-x text-center">
                <h4 class="text-center">"<?=$product->name?>" uspješno dodan u Vašu košaricu!</h4>
                <br>
                <br>
                <div class="large-6">
                  <button data-close class="button warning">Zatvori</button>
              </div>
              <div class="large-6">
                  <a href="<?=App::config('url')?>shoppingorder/index" data-close class="button expanded">Vaša košarica</a>
              </div>
            </div>
          </div>
          <!-- <i class="far fa-heart add-to-wishlist" data-id="<?= $product->id ?>" title="Dodaj &quot;<?= $product->name ?>&quot; u listu želja"></i> -->
        <?php else : ?>
          <i class="fas fa-cart-plus add-to-cart" title="Prijavite se ili registrirajte za dodavanje &quot;<?= $product->name ?>&quot; u Vašu košaricu." data-open="productprijava"></i>
          <!-- <i class="far fa-heart add-to-wishlist" title="Prijavite se ili registrirajte za dodavanje &quot;<?= $product->name ?>&quot; u Vašu listu želja." data-open="productprijava"></i> -->
        <?php endif; ?>
      </h4>
    </div>
    <!-- Product modal  -->
    <?php include 'productmodal.phtml' ?>
    <!--  -->

    <!-- Login modal if user is not logged in -->
    <?php include 'loginmodal.phtml' ?>
    <!--  -->
  </div>
</div>