<div class="large-3">
  <div class="card">
    <div class="card-divider" data-open="product<?= $product->id ?>" title="Kliknite na sliku za detalje!">
      <span>
        <?= $product->name ?>
      </span>
    </div>
    <img src="<?= $product->imageurl ?>" data-open="product<?= $product->id ?>" title="Kliknite na sliku za detalje!">
    <hr>
    <div class="card-section">
      <h4><?= $product->price ?> kn
      <?php if(App::authorized()):?>
        <i class="fas fa-cart-plus add-to-cart addToCart" data-id="<?=$product->id?>" title="Dodaj &quot;<?=$product->name?>&quot; u košaricu"></i>
        <i class="far fa-heart add-to-wishlist" data-id="<?=$product->id?>" title="Dodaj &quot;<?=$product->name?>&quot; u listu želja"></i>
      <?php else:?>
        <i class="fas fa-cart-plus add-to-cart" title="Prijavite se ili registrirajte za dodavanje &quot;<?=$product->name?>&quot; u Vašu košaricu." data-open="productprijava"></i>
        <i class="far fa-heart add-to-wishlist" title="Prijavite se ili registrirajte za dodavanje &quot;<?=$product->name?>&quot; u Vašu listu želja." data-open="productprijava"></i>
        <?php endif;?>
      </h4>
    </div>
    <!-- Product modal  -->
    <?php include 'productmodal.phtml' ?>
    <!--  -->
    
    <!-- Login modal if user is not logged in -->
    <?php include 'loginmodal.phtml' ?>
    <!--  -->
  </div>
</div>