<div class="small reveal" id="product<?= $product->id ?>" data-reveal>
      <h1 class="modal-product-name"><?= $product->name ?></h1>
      <div class="grid-x grid-padding-x modal-product-section">
        <div class="large-6 modal-product-image">
          <img src="<?= $product->imageurl ?>" alt="<?= $product->name ?>">
        </div>
        <div class="large-6 modal-product-description">
          <p><?= $product->description ?></p>
        </div>
      </div>
      <div class="grid-x grid-padding-x text-center">
        <div class="large-6 large-offset-1">
          <h3><?= $product->price ?> kn</h3>
        </div>
        <div class="large-3">
        <?php if(App::authorized()):?>
          <i class="fas fa-3x fa-cart-plus add-to-cart addToCart" data-id="<?= $product->id ?>" data-open="modal<?= $product->id ?>" title="Dodaj &quot;<?= $product->name ?>&quot; u košaricu"></i>
          <div class="small reveal add-modal" id="modal<?= $product->id ?>" data-reveal>
            <div class="grid-x grid-padding-x text-center">
                <h4 class="text-center">"<?=$product->name?>" uspješno dodan u Vašu košaricu!</h4>
                <br>
                <br>
                <div class="large-6">
                  <button data-close class="button warning">Zatvori</button>
              </div>
              <div class="large-6">
                  <a href="<?=App::config('url')?>shoppingorder/index" data-close class="button expanded">Vaša košarica</a>
              </div>
            </div>
          </div>        
          <i class="far fa-3x fa-heart add-to-wishlist" data-id="<?=$product->id?>" title="Dodaj &quot;<?=$product->name?>&quot; u listu želja." data-close></i>
      <?php else:?>
        <i class="fas fa-3x fa-cart-plus add-to-cart" title="Prijavite se ili registrirajte za dodavanje &quot;<?=$product->name?>&quot; u Vašu košaricu." data-open="productprijava"></i>
        <i class="far fa-3x fa-heart add-to-wishlist" title="Prijavite se ili registrirajte za dodavanje &quot;<?=$product->name?>&quot; u Vašu listu želja." data-open="productprijava"></i>
        <?php endif;?>
     </div>
      </div>
      <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>