<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?= App::config('appName') ?></div>
</div>

<!-- Development environment -->
<div class="development text-center">
  <?php if ($_SESSION['authorized']->user_role == 'oper') : ?>
    Operator panel
  <?php else : ?>
    Admin panel
  <?php endif; ?>
</div>
<br>


<div class="sidenav">
  <ul class="submenu menu vertical">
    <li><a href="<?= App::config('url') ?>" class="homepage"><?= App::config('appName') ?></a></li>
    <hr>
    <!-- CRUD start -->
    <li><a href="<?= App::config('url') ?>category/index">Kategorija</a></li>
    <li><a href="<?= App::config('url') ?>manufacturer/index">Proizvođači</a></li>
    <li><a href="<?= App::config('url') ?>product/index">Proizvod</a></li>
    <li><a href="<?= App::config('url') ?>order/index">Narudžbe</a></li>
    <li><a href="<?= App::config('url') ?>customer/index">Kupci</a></li>
    <li><a href="<?= App::config('url') ?>operator/index">Operateri</a></li>
    <!-- CRUD end -->
    <hr>
    <?php if (App::authorized()) : ?>
      <li><a href="<?= App::config('url') ?>login/logout">Odjava</a></li>
    <?php else : ?>
      <li><a href="<?= App::config('url') ?>login/index">Prijava</a></li>
    <?php endif; ?>
  </ul>
</div>