<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle></button>
    <div class="title-bar-title"><?= App::config('appName') ?></div>
</div>

<!-- Development environment -->
<?php if (App::config('dev') === true) {
    echo '<div class="development text-center">Development</div>';
} ?>

<!-- <div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><a href="<?= App::config('url') ?>" class="homepage"><?= App::config('appName') ?></a></li>
      <li><a href="#0">Admin/Operator</a>
        <ul class="submenu menu vertical" data-submenu>
            <li><a href="<?= App::config('url') ?>category/index">Kategorija</a></li>
            <li><a href="<?= App::config('url') ?>product/index">Proizvod</a></li>
            <li><a href="#0">Kupac</a></li>
          </ul>
      </li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <?php if (App::authorized()) : ?>
      <li><a href="<?= App::config('url') ?>login/logout">Odjava, <?= $_SESSION['authorized']->firstname ?></a></li>
      <?php else : ?>
      <li><a href="<?= App::config('url') ?>login/index">Prijava</a></li>
      <?php endif; ?>
    </ul>
  </div>
</div> -->

<div class="sidenav">
    <ul class="submenu menu vertical">
      <li><a href="<?= App::config('url') ?>" class="homepage"><?= App::config('appName')?></a></li>

        <li><a href="<?= App::config('url') ?>category/index">Category</a></li>
        <li><a href="<?= App::config('url') ?>product/index">Product</a></li>


        <?php if (App::authorized()) : ?>
            <li><a href="<?= App::config('url') ?>login/logout">Logout</a></li>
        <?php else : ?>
            <li><a href="<?= App::config('url') ?>login/index">Prijava</a></li>
        <?php endif; ?>
    </ul>
</div>