<div class="orbit" role="region" aria-label="Banner with discount" data-orbit>
  <div class="orbit-wrapper">
    <ul class="orbit-container">
      <li class="is-active orbit-slide">
        <figure class="orbit-figure">
          <img class="orbit-image" src="<?=App::config('url')?>public/images/banner/banner.webp" alt="Banner image" title="Registrirajte se i za prvu kupnju dobivate 20% popusta!">
        </figure>
      </li>
      <li class="orbit-slide">
        <figure class="orbit-figure">
          <img class="orbit-image" src="<?=App::config('url')?>public/images/banner/freeShipping.jpg" alt="Banner image" title="Besplatna dostava iznad 400kn!">
        </figure>
      </li>
    </ul>
  </div>
</div>