<?php if (isset($_SESSION['authorized']->user_role) && ($_SESSION['authorized']->user_role == 'admin' || $_SESSION['authorized']->user_role == 'oper')) : ?>
    <div class="footer-main">
        <div class="footer">
            <h2>
                <?= App::config('appName') ?> &copy; 2022
            </h2>
        </div>
    </div>
<?php else : ?>
    <div class="footer-main">
        <div class="footer">
            <div class="grid-x">
                <div class="large-3">
                    <h3>Roman Grubić</h3>
                <div><a href="https://github.com/romangrubic" target="_blank" rel="noopener noreferrer">Github</a></div>
                <div><a href="https://www.linkedin.com/in/roman-grubic/" target="_blank" rel="noopener noreferrer">LinkedIn</a></div>
                </div>
                <div class="large-6">
                    <p>Primajte novosti i posebne akcije na Vaš email!</p>
                    <form action="<?= App::config('url') ?>index/emailNewsletter" method="post">
                        <input type="email" name="email" id="email" placeholder="Unesite Vaš email!">
                        <input type="submit" class="email-submit button" value="Pošalji!">
                        <input type="hidden" name="currentPage" value="<?= substr($_SERVER['REQUEST_URI'], 1) ?>">
                    </form>
                    <h2>
                        <?= App::config('appName') ?> &copy; 2022
                    </h2>
                </div>
            </div>

        </div>
    </div>
<?php endif; ?>