<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?=App::config('appName')?></title>
<link rel="stylesheet" href="<?=App::config('url')?>public/css/foundation.css">
<link rel="stylesheet" href="<?=App::config('url')?>public/css/app.css">  

<!-- CSS for autocomplete Jquery -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">

<!-- Custom CSS loading -->
<?php if(isset($css)):?>
    <link rel="stylesheet" href="<?= App::config('url')?>public/css/<?=$css?>">  
<?php endif;?>
<!--  -->