<?php if(App::authorized()):?>
    <div class="top-bar-right large-1 cell">
<?php else:?>
    <div class="top-bar-right large-2 cell">
<?php endif;?>
    <ul class="menu blue-sky">
        <?php if (App::authorized()) : ?>
            <form action="<?= App::config('url') ?>login/logout" method="post">
                <input type="hidden" name="currentPage" value="<?= substr($_SERVER['REQUEST_URI'], 1) ?>">
                <input type="submit" class="button warning expanded" value="Odjava, <?= $_SESSION['authorized']->firstname ?>">
            </form>
        <?php else : ?>
            <button class="button login-button" type="button" data-toggle="login-form">Prijavite se!</button>
            <div class="dropdown-pane" id="login-form" data-position="bottom" data-alignment="center" data-dropdown data-auto-focus="true">
                <form class="log-in-form" action="<?= App::config('url') ?>login/authorize" method="POST">
                    <p class="text-center">Ukoliko nemate račun, registrirajte se <a href="<?= App::config('url') ?>registration/index">ovdje.</a></p>
                    <label for="email">Vaš email</label>
                    <input type="email" name="email" id="email" class="log-in-form-input" aria-describedby="messageEmail" placeholder="vas.email@gmail.com" value="<?= $email ?>">
                    <p class="help-text red-message" id="messageEmail">
                        <?= $message->email ?>
                    </p>
                    <label for="user_password">Vaša lozinka</label>
                    <input type="password" name="user_password" id="user_password" class="log-in-form-input" aria-describedby="messagePassword">
                    <p class="help-text red-message" id="messagePassword">
                        <?= $message->password ?>
                    </p>

                    <input type="hidden" name="currentPage" value="<?= substr($_SERVER['REQUEST_URI'], 1) ?>">
                    <div class="text-center ">
                    <input type="submit" class="expanded prijava-button" value="Prijava" />
                    </div>
                    
                    <?php if (isset($message->logout)) : ?>
                        <p class="help-text red-message">
                            <?= $message->logout ?>
                        </p>
                    <?php endif; ?>
                </form>
                        <br>
                        <li>* Ekskluzivni popusti za članove kluba</li>
                        <li>* Brzo i jednostavno naručivanje</li>
                        <li>* Pratite svoje narudžbe i njihovu povijest</li>
                    <hr>
                    Uloga: kupac
                <br>
                Email: r.knezevic@mojatrgovina.com
                <br>
                Lozinka: a
                <br>
                <br>
                Uloga: admin
                <br>
                Email: admin@edunova.hr
                <br>
                Lozinka: a
                <br>
                <br>
                Uloga: operator
                <br>
                Email: oper@edunova.hr
                <br>
                Lozinka: o
                <br>
                <br>
                
            </div>
        <?php endif; ?>
    </ul>
</div>