<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?=App::config('appName')?></div>
</div>

<!-- Banner with current discounts and promotions -->
<img src="<?=App::config('url')?>public/images/banner.webp" alt="Banner image" title="Registrirajte se i za prvu kupnju dobivate 20% popusta!">

<!-- Development environment -->
<?php if(App::config('dev') === true){echo '<div class="development text-center">Development</div>';}?>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><?=App::config('appName')?></li>
      <li class="has-submenu">
        <a href="#0">One</a>
        <ul class="submenu menu vertical" data-submenu>
          <li><a href="#0">One</a></li>
          <li><a href="#0">Two</a></li>
          <li><a href="#0">Three</a></li>
        </ul>
      </li>
      <li><a href="#0">Two</a></li>
      <li><a href="#0">Three</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <?php if(App::authorized()): ?>
      <li><a href="<?= App::config('url') ?>login/logout">Odjava</a></li>
      <?php else:?>
      <li><a href="<?= App::config('url') ?>login/index">Login</a></li>
      <?php endif;?>
    </ul>
  </div>
</div>
