<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?=App::config('appName')?></div>
</div>

<!-- Banner with current discounts and promotions -->
<?php if($_SERVER['REQUEST_URI'] === '/'):?>
<img src="<?=App::config('url')?>public/images/banner.webp" alt="Banner image" title="Registrirajte se i za prvu kupnju dobivate 20% popusta!">
<?php endif;?>
<!-- Development environment -->
<?php if(App::config('dev') === true){echo '<div class="development text-center">Development</div>';}?>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><a href="<?=App::config('url')?>" class="homepage"><?=App::config('appName')?></a></li>
      <li class="has-submenu">
        <a href="<?=App::config('url')?>product/index">Proizvodi</a>
        <ul class="submenu menu vertical" data-submenu>
          <!-- Category list -->
          <li><a href="<?=App::config('url')?>product/index/1">Tipkovnica</a></li>
          <li><a href="<?=App::config('url')?>product/index/2">Miš</a></li>
          <li><a href="<?=App::config('url')?>product/index/4">Matična ploča</a></li>
        </ul>
      </li>
      <li><a href="#0">Two</a></li>
      <?php if(App::authorized()):?>
      <li><a href="<?=App::config('url')?>dashboard/index">Nadzorna ploča</a></li>
      <?php endif;?>
      <?php if(App::authorized() && ($_SESSION['authorized']->user_role === 'oper' || $_SESSION['authorized']->user_role === 'admin')):?>
      <li><a href="#0">Admin/Operator</a>
        <ul class="submenu menu vertical" data-submenu>
            <li><a href="<?=App::config('url')?>category/index">Kategorija</a></li>
            <li><a href="#0">Proizvod</a></li>
            <li><a href="#0">Kupac</a></li>
          </ul>
      </li>
      <?php endif;?>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <?php if(App::authorized()): ?>
      <li><a href="<?= App::config('url') ?>login/logout">Odjava, <?=$_SESSION['authorized']->firstname?></a></li>
      <?php else:?>
      <li><a href="<?= App::config('url') ?>login/index">Prijava</a></li>
      <?php endif;?>
    </ul>
  </div>
</div>
