<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?=App::config('appName')?></div>
</div>

<!-- Banner with current discounts and promotions -->
<!-- <?php include 'banner.phtml';?> -->
<!-- Development environment -->
<?php if(App::config('dev') === true){echo '<div class="development text-center">Development</div>';}?>
<div class="top-bar grid-x" id="example-menu">
  <div class="top-bar-left ">
    <ul class="dropdown menu grid-x" data-dropdown-menu>
      <li class="menu-text large-2 cell"><a href="<?=App::config('url')?>" class="homepage"><?=App::config('appName')?></a></li>
      <!-- Search product form -->
      <form class="search-product large-6 cell blue-sky" action="<?=App::config('url')?>product/index" method="get">
      <div class="ui-widget">
          <input type="text" name="search" id="search" class="search-product" placeholder="Traži po imenu proizvoda ili proizvođaču..." <?=(isset($_GET['search']))? 'value="'.$_GET['search'].'"':''?>>
      </div>
      </form>
      <!-- Dashboard link -->
      <?php if(App::authorized()):?>
      <li class="menu-text large-1 cell"><a class="homepage" href="<?=App::config('url')?>dashboard/index">Vaš profil</a></li>

      <!-- For the badge -->
      <?php $number= Shoppingorder::numberOfUniqueProducts($_SESSION['authorized']->id);?>
      <li class="menu-text large-1 cell shopping-icon" id="shopping-icon"><a class="shopping-cart" href="<?=App::config('url')?>shoppingorder/index"><i  style="color: white;" class="fas fa-2x fa-shopping-cart"><?=($number > 0) ? '<span class="badge warning">'.$number.'</span>' : '';?></i> </a></li>
      <?php endif;?>
    
      <!-- Login form dropdown -->
      <?php if(Request::getRoute() != '/registration/index'){
        include 'loginForm.phtml';
      }
    ?>
    </ul>
  </div>
</div>
<!-- Category list -->
<div class="top-bar cat-bar">
  <div class="cat-menu">
    <ul class="menu" id="cat-menu">
    <li class="cat-button"><a href="<?=App::config('url')?>product/index">Svi proizvodi</a></li>
      <?php foreach(Category::read() as $category):?>
        <li class="cat-button"><a href="<?=App::config('url')?>product/index/<?=$category->id?>"><?=$category->name?></a></li>
        <?php endforeach;?>
    </ul>
  </div>
</div>
<br>
