<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?=App::config('appName')?></div>
</div>

<!-- Banner with current discounts and promotions -->
<?php include 'banner.phtml';?>
<!-- Development environment -->
<?php if(App::config('dev') === true){echo '<div class="development text-center">Development</div>';}?>
<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><a href="<?=App::config('url')?>" class="homepage"><?=App::config('appName')?></a></li>
      <li>
        <a href="<?=App::config('url')?>product/index">Proizvodi</a>
        <ul class="submenu menu vertical" data-submenu>
          <!-- Category list -->
          <li><a href="<?=App::config('url')?>product/index">Svi proizvodi</a></li>
          <li><a href="<?=App::config('url')?>product/index/1">Tipkovnica</a></li>
          <li><a href="<?=App::config('url')?>product/index/2">Miš</a></li>
          <li><a href="<?=App::config('url')?>product/index/4">Matična ploča</a></li>
        </ul>
      </li>
      <?php if(App::authorized()):?>
      <li><a href="<?=App::config('url')?>dashboard/index">Nadzorna ploča</a></li>
      <?php endif;?>
      <?php if(App::authorized() && isset($_SESSION['authorized']->user_role) && ($_SESSION['authorized']->user_role === 'oper' || $_SESSION['authorized']->user_role === 'admin')):?>
      <li><a href="#0">Admin/Operator</a>
        <ul class="submenu menu vertical" data-submenu>
            <li><a href="<?=App::config('url')?>category/index">Kategorija</a></li>
            <li><a href="<?=App::config('url')?>product/index">Proizvod</a></li>
            <li><a href="#0">Kupac</a></li>
          </ul>
      </li>
      <?php elseif(App::authorized() && !isset($_SESSION['authorized']->user_role)):?>
      <?php endif;?>
    </ul>
  </div>
  <!-- Login form dropdown -->
  <?php if(Request::getRoute() != '/registration/index'){
    include 'loginForm.phtml';
  }
    ?>
</div>
<!-- Category list -->
<div class="top-bar" id="example-menu">
  <div class="cat-menu">
    <ul class="menu" id="cat-menu">
      <?php foreach(Category::read() as $category):?>
        <li><a href="<?=App::config('url')?>product/index/<?=$category->id?>"><?=$category->name?></a></li>
        <?php endforeach;?>
    </ul>
  </div>
</div>
<br>
