<script src="<?=App::config('url')?>public/js/vendor/jquery.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
<script src="<?=App::config('url')?>public/js/vendor/what-input.js"></script>
<script src="<?=App::config('url')?>public/js/vendor/foundation.js"></script>
<script src="<?=App::config('url')?>public/js/app.js"></script> 

<?php if(isset($_SESSION['authorized']->user_role) && ($_SESSION['authorized']->user_role == 'admin' || $_SESSION['authorized']->user_role == 'oper')):?>

<?php else:?>
<script src="<?=App::config('url')?>public/js/custom/searchAutocomplete.js"></script> 
<?php endif;?>
<?php if(App::authorized()):?>
<script src="<?=App::config('url')?>public/js/custom/addToCart.js"></script> 
<?php endif;?>
<!-- Fontawesome -->
<script src="https://kit.fontawesome.com/41a908fb89.js" crossorigin="anonymous"></script>

<!-- Custom Javascript -->
<?php if(isset($javascript)) echo $javascript;?>