<script src="<?=App::config('url')?>public/js/vendor/jquery.js"></script>
<script src="<?=App::config('url')?>public/js/vendor/what-input.js"></script>
<script src="<?=App::config('url')?>public/js/vendor/foundation.js"></script>
<script src="<?=App::config('url')?>public/js/app.js"></script> 
<!-- Fontawesome -->
<script src="https://kit.fontawesome.com/41a908fb89.js" crossorigin="anonymous"></script>