<div class="main-index">
    <div class="form">
        <form action="<?= App::config('url') ?>operator/change" method="post">
            <hr>
            <fieldset>
                <legend>Detalji operatera</legend>


                <label for="user_password">Stara Lozinka</label>
                <input type="password" name="user_password" id="user_password" aria-describedby="messagepassword">
                <p class="help-text red-message" id="messagepassword">
                    <?= $message->user_password ?>
                </p>

                <label for="user_password">Nova Lozinka</label>
                <input type="password" name="user_password_new" id="user_password_new" aria-describedby="messagepasswordnew">
                <p class="help-text red-message" id="messagepasswordnew">
                    <?= $message->user_password_new ?>
                </p>

                <label for="user_password_repeat">Ponovno unesite lozinku</label>
                <input type="password" name="user_password_new_repeat" id="user_password_new_repeat" aria-describedby="messagePasswordRepeat">
                <p class="help-text red-message" id="messagePasswordRepeat">
                    <?= $message->user_password_new_repeat ?>
                </p>

                <input type="hidden" name="id" value="<?= $operator->id ?>">

                <div class="grid-x grid-padding-x">
                    <div class="large-4 cell">
                        <a class="alert button expanded" href="<?= App::config('url') ?>operator/index">Odustani</a>
                    </div>
                    <div class="large-8 cell">
                        <input type="submit" class="button expanded" value="Promijeni lozinku">
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>